name: 'install-nvm'
description: 'Installs NODE versions'
author: 'Seidor'
inputs:
  CFG_FILE:
    description: 'Path to your config.yml file'
    default: '.github/config/config.yml'

runs:
  using: composite
  steps:
    - name: 'install nvm & node'
      shell: bash -e {0}
      run: |
        CFG_FILE="$GITHUB_WORKSPACE/${{ inputs.CFG_FILE }}"
        source $HOME/.nvm/nvm.sh
        for VERSION in $(yq e '.node_version | keys | .[]' "$CFG_FILE"); do nvm install $VERSION; done
        nvm ls --no-alias && nvm use $VERSION && node -v && nvm -v
