name: 'install-node-modules'
description: 'Installs cartridges'
author: 'Seidor'

runs:
  using: composite
  steps:
    - name: 'install node modules'
      shell: bash -el {0}
      run: |
        for VERSION in $(yq e '.node_version | keys | .[]' ${{ env.CFG_FILE }}); do
          node -v && nvm use $VERSION && node -v
          echo "Installing cartridges for version $VERSION:"
          for CARTRIDGE in $(yq e '.node_version."'"$VERSION"'" | keys | .[]' ${{ env.CFG_FILE }}); do
            FOLDER=$(yq e '.node_version."'"$VERSION"'"."'"$CARTRIDGE"'".path' ${{ env.CFG_FILE }})
            cd $GITHUB_WORKSPACE/$FOLDER
            #INSTALL=$(yq e '.node_version."'"$VERSION"'"."'"$CARTRIDGE"'".installation' ${{ env.CFG_FILE }})
            #$INSTALL
            npm install
            echo "$CARTRIDGE installed"
          done
        done
        echo "Information: Project setup completed"
