name: 'install-node-modules'
description: 'Installs cartridges'
author: 'Seidor'
inputs:
  CFG_FILE:
    description: 'Path to your config.yml file'
    default: '.github/config/config.yml'

runs:
  using: composite
  steps:
    - name: 'install node modules'
      shell: bash -el {0}
      run: |
        for VERSION in $(yq e '.node_version | keys | .[]' "${{ inputs.CFG_FILE }}"); do
          node -v && nvm use $VERSION && node -v
          echo "Installing cartridges for version $VERSION:"
          for CARTRIDGE in $(yq e '.node_version."'"$VERSION"'" | keys | .[]' "${{ inputs.CFG_FILE }}"); do
            FOLDER=$(yq e '.node_version."'"$VERSION"'"."'"$CARTRIDGE"'".path' "${{ inputs.CFG_FILE }}")
            cd "$GITHUB_WORKSPACE/$FOLDER"
            npm install
            echo "$CARTRIDGE installed"
          done
        done
        echo "Information: Project setup completed"
