name: 'install-node-modules'
description: 'Installs cartridges'
author: 'Seidor'
inputs:
  CFG_FILE:
    description: 'Path to your config.yml file'
    default: '.github/config/config.yml'

runs:
  using: composite
  steps:
    - name: 'install node modules'
      shell: bash -e {0}
      run: |
        CFG_FILE="$GITHUB_WORKSPACE/${{ inputs.CFG_FILE }}"
        source $HOME/.nvm/nvm.sh
        for VERSION in $(yq e '.node_version | keys | .[]' "$CFG_FILE"); do
          node -v && nvm use $VERSION && node -v
          echo "Installing cartridges for version $VERSION:"
          for CARTRIDGE in $(yq e '.node_version."'"$VERSION"'" | keys | .[]' "$CFG_FILE"); do
            FOLDER=$(yq e '.node_version."'"$VERSION"'"."'"$CARTRIDGE"'".path' "$CFG_FILE")
            cd "$GITHUB_WORKSPACE/$FOLDER"
            npm install
            echo "$CARTRIDGE installed"
          done
        done
        echo "Information: Project setup completed"
