name: Configure Github Write Credentials
description: Configure Action with Github Write Credentials on repository
author: "seidor"
inputs:
  actor:
    description: 'User name'
    required: true
  email:
    description: 'user Email'
    required: true
  secret:
    description: 'Github Secret'
    required: true
  config:
    description: 'Git Config'
    required: true
runs:
  using: composite  
  steps:
    - run: /bin/bash $GITHUB_ACTION_PATH/add-ssh-write-credentials.sh actor_name=${{ inputs.actor }} actor_mail=${{ inputs.email}} secret=${{ inputs.secret }} config=${{ inputs.config }}"
      shell: bash