name: 'Lint ISML issues'
description: 'Iterates through all changed files and lints ISML files'
author: 'Seidor'
inputs:
  ALL_CHANGED_FILES:
    description: 'All changed files in the PR'
    required: true
  WORKING_DIRECTORY:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - name: 'Lint ISML issues'
      shell: bash
      run: |
        FILES_ISML=$(echo "${{ inputs.ALL_CHANGED_FILES }}" | tr ' ' '\n' | grep -E ".isml$" | while read -r FILE; do echo "$GITHUB_WORKSPACE/$FILE"; done | xargs)
        cd ${{ inputs.WORKING_DIRECTORY }}
        npm run lint:isml:ci -- $FILES_ISML
