name: 'install-nvm'
description: 'Installs NVM & NODE versions'
author: 'Seidor'
inputs:
  URI:
    description: 'URI to nvm installation script'
    default: 'https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh'

runs:
  using: composite
  steps:
    - name: 'install nvm & node'
      shell: bash -e {0}
      run: |
        curl -o- ${{ inputs.URI }} | bash -e
