name: 'install-nvm'
description: 'Installs NVM & NODE versions'
author: 'Seidor'

runs:
  using: composite
  steps:
    - name: 'install nvm & node'
      shell: bash -e {0}
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash -e
        cat ~/.bashrc
        source $HOME/.nvm/nvm.sh
        for VERSION in $(yq e '.node_version | keys | .[]' ${{ env.CFG_FILE }}); do nvm install $VERSION; done
        nvm ls --no-alias && nvm use $VERSION && node -v && nvm -v
