name: 'create-artifact'
description: 'Creates the code-version "Artifact"'
author: 'Seidor'
inputs:
  BUILD_NUMBER:
    description: '(Tag, Release, etc.)'
    required: true

runs:
  using: composite
  steps:
    - name: 'Create the code-version "Artifact"'
      shell: bash -e {0}
      run: |
        cd "$GITHUB_WORKSPACE"
        chmod +x ./build.sh
        ./build.sh "${{ inputs.BUILD_NUMBER }}"
        mv "./temp/${{ inputs.BUILD_NUMBER }}" "${{ inputs.BUILD_NUMBER }}"
        zip -qq -r "./${{ inputs.BUILD_NUMBER }}.zip" "./${{ inputs.BUILD_NUMBER }}"
