name: 'install-yq'
description: 'Installs yq command to process yml files'
author: 'Seidor'

runs:
  using: composite
  steps:
    - name: 'install yq'
      shell: bash -e {0}
      run: |
        #sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
        mkdir -p ~/bin
        wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ~/bin/yq
        chmod +x ~/bin/yq
        source .profile
