name: 'Lint JS issues'
description: 'Iterates through all changed files and lints JS files'
author: 'Seidor'
inputs:
  ALL_CHANGED_FILES:
    description: 'All changed files in the PR'
    required: true
  CFG_LINT_FILE:
    description: 'Path to your lint.yml file'
    default: '.github/config/lint.yml'

runs:
  using: composite
  steps:
    - name: 'Lint JS issues'
      shell: bash -e {0}
      run: |
        CFG_LINT_FILE="$GITHUB_WORKSPACE/${{ inputs.CFG_LINT_FILE }}"
        for VERSION in $(yq e '.node_version | keys | .[]' "$CFG_LINT_FILE"); do
          for CARTRIDGE in $(yq e '.node_version."'"$VERSION"'" | keys | .[]' "$CFG_LINT_FILE"); do
            FOLDER=$(yq e '.node_version."'"$VERSION"'"."'"$CARTRIDGE"'".path' "$CFG_LINT_FILE")
            FILES_JS=$(echo "${{ inputs.ALL_CHANGED_FILES }}" | tr ' ' '\n' | grep -E ".js$" | while read -r FILE; do echo "$GITHUB_WORKSPACE/$FILE"; done | grep $FOLDER | xargs)
            if [ -n "$FILES_JS" ]; then
              echo "Linting files in $FOLDER"
              cd "$GITHUB_WORKSPACE/$FOLDER" && npm run lint:js:ci -- $FILES_JS || { echo "Linting failed in $FOLDER"; false; }
            else
              echo "No files to lint in $FOLDER"
            fi
          done
        done
        cd "$GITHUB_WORKSPACE"
