name: 'assure-sandbox-up'
description: 'Makes sure the sandbox is in started state'
author: 'Seidor'
inputs:
  SANDBOX_ID:
    description: 'Sandbox ID'
    required: true
  SFCC_TOKEN:
    description: 'Token used for authentication in api calls'
    required: true
  TIMEOUT:
    description: 'Timeout in seconds'
    default: '300'

runs:
  using: composite
  steps:
    - name: 'assure-sandbox-up'
      shell: bash -e {0}
      run: |
        STATE=""
        END_TIME=$((SECONDS + ${{ inputs.TIMEOUT }}))

        while [ $SECONDS -lt $END_TIME ]; do
          RESPONSE=$(curl --location "https://admin.dx.commercecloud.salesforce.com/api/v1/sandboxes/${{ inputs.SANDBOX_ID }}" \
          --header "accept: application/json" \
          --header "Authorization: Bearer ${{ inputs.SFCC_TOKEN }}")

          echo $RESPONSE
          STATE=$(echo $RESPONSE | jq -r '.data.state')

          if [ "$STATE" == "started" ]; then
            echo "Sandbox is in started state."
            exit 0
          fi

          sleep 30
        done

        echo "Sandbox did not start within the time limit."
        exit 1
