name: 'compile-statics'
description: 'Compilation step'
author: 'Seidor'
inputs:
  CFG_FILE:
    description: 'Path to your config.yml file'
    default: '.github/config/config.yml'

runs:
  using: composite
  steps:
    - name: 'Compile Statics'
      shell: bash -el {0}
      run: |
        CFG_FILE="$GITHUB_WORKSPACE/${{ inputs.CFG_FILE }}"
        for VERSION in $(yq e '.node_version | keys | .[]' "$CFG_FILE"); do
          node -v && nvm use $VERSION && node -v
          echo "Compiling statics for version $VERSION:"
          for CARTRIDGE in $(yq e '.node_version."'"$VERSION"'" | keys | .[]' "$CFG_FILE"); do
            FOLDER=$(yq e '.node_version."'"$VERSION"'"."'"$CARTRIDGE"'".path' "$CFG_FILE")
            cd "$GITHUB_WORKSPACE/$FOLDER"
            echo "Compiling statics for cartridge $CARTRIDGE:"
            yq e '.node_version."'"$VERSION"'"."'"$CARTRIDGE"'".compilation | .[]' "$CFG_FILE" | xargs -I {} bash -e -c "{}"
            echo "Statics for cartridge $CARTRIDGE have been compiled"
          done
        done
        echo "Information: Project compilation completed"
