name: 'create-artifact'
description: 'Creates the code-version "Artifact"'
author: 'Seidor'

inputs:
  CFG_FILE:
    description: 'Path to your config.yml file'
    default: '.github/config/config.yml'

runs:
  using: composite
  steps:
    - name: 'Create the code-version "Artifact"'
      run: /bin/bash $GITHUB_ACTION_PATH/unit-tests.sh config_file=${{ inputs.CFG_FILE }}
      shell: bash