name: 'unit-tests'
description: 'Executes unit tests'
author: 'Seidor'

inputs:
  CFG_FILE:
    description: 'Path to your unit_tests.yml config file'
    default: '.github/config/unit_tests.yml'

runs:
  using: composite
  steps:
    - name: 'unit tests'
      shell: bash -e {0}
      run: |
        CFG_FILE="$GITHUB_WORKSPACE/${{ inputs.CFG_FILE }}"
        source $HOME/.nvm/nvm.sh
        for VERSION in $(yq e '.node_version | keys | .[]' "$CFG_FILE"); do
          node -v && nvm use $VERSION && node -v
          for CARTRIDGE in $(yq e '.node_version."'"$VERSION"'" | keys | .[]' "$CFG_FILE"); do
            echo "Executing Unit tests for cartridge: $CARTRIDGE"
            CARTRIDGE_DIR=$(yq e '.node_version."'"$VERSION"'"."'"$CARTRIDGE"'".path' "$CFG_FILE")
            cd "$GITHUB_WORKSPACE/$CARTRIDGE_DIR" && $(yq '.node_version."'"$VERSION"'"."'"$CARTRIDGE"'".cover' "$CFG_FILE")
          done
        done
        echo "Information: Unit tests execution success"

      #run: /bin/bash $GITHUB_ACTION_PATH/unit-tests.sh config_file=${{ inputs.CFG_FILE }}
      #shell: bash