name: Build Container Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
      options: "--entrypoint " 

    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run: TAG=$(grep -i "version" Dockerfile |cut -d '"' -f2) && \
          mkdir -p /kaniko/.docker && \
          echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json  && \
          /kaniko/executor --skip-tls-verify --context "${{ github.workspace }}" --dockerfile "${{ github.workspace }}/Dockerfile" --destination "${CI_REGISTRY_IMAGE}:${TAG}" --destination "${CI_REGISTRY_IMAGE}:latest"