name: 'Build container for CI'
description: 'A simple GitHub Action for build and publish container images over Github Container Registry'
author: 'Seidor'
inputs:
  build_revision:
    description: 'The SHA-1 of the git commit for which the build is running. Default to GITHUB_SHA.'
    required: false
    default: ${{ github.sha }}
  verbose:
    description: 'Verbose output'
    required: false
    default: "true"
  token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
  container_name:
    description: 'Container image name'
    required: false
    default: ${{ github.repository }}
  container_tag:
    description: 'Container image tag'
    required: false
    default: ${{ github.sha }}
  build_context:
    description: 'Context to build application'
    required: false
    default: ./
  dockerfile:
    description: 'Input file'
    required: false
    default: Dockerfile
outputs:
  container_image_url:
    description: "URL to the container image's new location"
runs:
  image: 'docker://gcr.io/kaniko-project/executor:debug'
  using: 'docker'
  main: 'entrypoint.sh'

