name: 'auth-and-set-default-instance'
description: 'Authenticates and sets the default instance'
author: 'Seidor'
inputs:
  CLIENT_ID:
    description: 'Client ID for authentication'
    required: true
  CLIENT_SECRET:
    description: 'Client secret for authentication'
    required: true
  INSTANCE_URL:
    description: 'Instance URL'
    required: true
  TOOLS_FOLDER:
    description: 'Path to your salesforce tools folder'
    required: true
  DEFAULT_INSTANCE:
    description: 'Whether or not to set instance as default'
    default: 'false'

runs:
  using: composite
  steps:
    - name: 'Authenticate and set default instance'
      shell: bash -el {0}
      run: |
        node ${{ inputs.TOOLS_FOLDER }}/node_modules/sfcc-ci/cli.js "client:auth" "${{ inputs.CLIENT_ID }}" "${{ inputs.CLIENT_SECRET }}"
        if [ "${{ inputs.DEFAULT_INSTANCE }}" = "true" ]; then
          node ${{ inputs.TOOLS_FOLDER }}/node_modules/sfcc-ci/cli.js "instance:add" ${{ inputs.INSTANCE_URL }} -d
        fi
