name: 'auth-and-set-default-instance'
description: 'Authenticates and sets the default instance'
author: 'Seidor'
inputs:
  CLIENT_ID:
    description: 'Client ID for authentication'
    required: true
  CLIENT_SECRET:
    description: 'Client secret for authentication'
    required: true
  INSTANCE_URL:
    description: 'Instance URL'
    required: true
  TOOLS_FOLDER:
    description: 'Path to your salesforce tools folder'
    required: true
  SET_DEFAULT_INSTANCE:
    description: 'Whether or not to set instance as default'
    default: 'false'
outputs:
  SFCC_TOKEN:
    description: 'Token used for authentication in api calls'
    value: ${{ steps.token.outputs.SFCC_TOKEN }}

runs:
  using: composite
  steps:
    - name: 'Authenticate and set default instance'
      id: 'token'
      shell: bash -el {0}
      run: |
        TOOLS_FOLDER="$GITHUB_WORKSPACE/${{ inputs.TOOLS_FOLDER }}"
        ADD_DEFAULT_INSTANCE=$([ "${{ inputs.SET_DEFAULT_INSTANCE }}" = "true" ] && echo "-d" || echo "")
        TOKEN=""
        
        node "$TOOLS_FOLDER/node_modules/sfcc-ci/cli.js" "client:auth" ${{ inputs.CLIENT_ID }} ${{ inputs.CLIENT_SECRET }}
        TOKEN=$(node "$TOOLS_FOLDER/node_modules/sfcc-ci/cli.js" "client:auth:token")
        echo "SFCC_TOKEN=$TOKEN" >> $GITHUB_OUTPUT

        node "$TOOLS_FOLDER/node_modules/sfcc-ci/cli.js" "instance:add" ${{ inputs.INSTANCE_URL }} ${ADD_DEFAULT_INSTANCE}
