name: 'Lint SCSS issues'
description: 'Iterates through all changed files and lints SCSS files'
author: 'Seidor'
inputs:
  ALL_CHANGED_FILES:
    description: 'All changed files in the PR'
    required: true
  WORKING_DIRECTORY:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - name: 'Lint SCSS issues'
      shell: bash
      run: |
        FILES_CSS=$(echo "$GITHUB_WORKSPACE/${{ inputs.ALL_CHANGED_FILES }}" | tr ' ' '\n' | grep  -E ".scss$" | xargs)
        cd ${{ inputs.WORKING_DIRECTORY }}
        npm run lint:css:ci -- $FILES_CSS
