name: 'upload-and-activate'
description: 'Uploads code version (and activates IF ACTIVATE TRUE)'
author: 'Seidor'
inputs:
  ENVIRONMENT:
    description: 'Environment'
    required: true
  INSTANCE_URL:
    description: 'Instance URL'
    required: true
  CERT_FILE:
    description: 'Path to your certificate file'
  CERT_INSTANCE_URL:
    description: 'URL for cert instance'
  CERTIFICATE_PASSWORD:
    description: 'Secret for the certificate'
  TOOLS_FOLDER:
    description: 'Path to your salesforce tools folder'
    required: true
  BUILD_NUMBER:
    description: 'Tag, Release, etc.'
    required: true
  ACTIVATE:
    description: 'Whether or not to activate the code version'
    default: 'false'

runs:
  using: composite
  steps:
    - name: 'Upload and activate code version'
      shell: bash -el {0}
      run: |
        TOOLS_FOLDER="$GITHUB_WORKSPACE/${{ inputs.TOOLS_FOLDER }}"
        CERT_FILE="$GITHUB_WORKSPACE/${{ inputs.CERT_FILE }}"
        ENV_URL=$([ "${{ inputs.ENVIRONMENT }}" = "staging" ] && echo "${{ inputs.CERT_INSTANCE_URL }}" || echo "${{ inputs.INSTANCE_URL }}")
        CERT_PARAMS=$([ "${{ inputs.ENVIRONMENT }}" = "staging" ] && echo "-c \"$CERT_FILE\" -p "${{ inputs.CERTIFICATE_PASSWORD }}"" || echo "")
        ACTIVATE_FLAG=$([ "${{ inputs.ACTIVATE }}" = "true" ] && echo "-a" || echo "")
        
        node "$TOOLS_FOLDER/node_modules/sfcc-ci/cli.js" "code:deploy" "./${{ inputs.BUILD_NUMBER }}.zip\" -i $ENV_URL $CERT_PARAMS $ACTIVATE_FLAG
        #echo "node \"$TOOLS_FOLDER/node_modules/sfcc-ci/cli.js\" \"code:deploy\" \"./${{ inputs.BUILD_NUMBER }}.zip\" -i $ENV_URL $CERT_PARAMS $ACTIVATE_FLAG"
