name: 'upload-and-activate'
description: 'Uploads code version (and activates IF ACTIVATE TRUE)'
author: 'Seidor'
inputs:
  ENVIRONMENT:
    description: 'Environment'
  ENVIRONMENT_URL:
    description: 'Environment URL'
    required: true
  CERT_FILE:
    description: 'The path to your certificate file'
  CERT_INSTANCE_URL:
    description: 'URL for cert instance'
    required: true
  CERTIFICATE_PASSWORD:
    description: 'Secret for the certificate'
    required: true
  TOOLS_FOLDER:
    description: 'The path to your salesforce tools folder'
  BUILD_NUMBER:
    description: 'Tag, Release, etc.'
  ACTIVATE:
    description: 'Whether or not to activate the code version'

runs:
  using: composite
  steps:
    - name: 'Upload and activate code version'
      shell: bash -el {0}
      run: |
        if [ "${{ inputs.ENVIRONMENT }}" = "staging" ]; then
          if [ "${{ inputs.ACTIVATE }}" = "true" ]; then
            node ${{ inputs.TOOLS_FOLDER }}/node_modules/sfcc-ci/cli.js "code:deploy" "./${{ inputs.BUILD_NUMBER }}.zip" -i ${{ inputs.CERT_INSTANCE_URL }} -c "${{ inputs.CERT_FILE }}" -p "${{ inputs.CERTIFICATE_PASSWORD }}" -a
          else
            node ${{ inputs.TOOLS_FOLDER }}/node_modules/sfcc-ci/cli.js "code:deploy" "./${{ inputs.BUILD_NUMBER }}.zip" -i ${{ inputs.CERT_INSTANCE_URL }} -c "${{ inputs.CERT_FILE }}" -p "${{ inputs.CERTIFICATE_PASSWORD }}"
          fi
        else
          if [ "${{ inputs.ACTIVATE }}" = "true" ]; then
            node ${{ inputs.TOOLS_FOLDER }}/node_modules/sfcc-ci/cli.js "code:deploy" "./${{ inputs.BUILD_NUMBER }}.zip" -i "${{ inputs.ENVIRONMENT_URL }}" -a
          else
            node ${{ inputs.TOOLS_FOLDER }}/node_modules/sfcc-ci/cli.js "code:deploy" "./${{ inputs.BUILD_NUMBER }}.zip" -i "${{ inputs.ENVIRONMENT_URL }}"
          fi
        fi
