name: 'Merge Branches'
description: 'A simple GitHub Action for merge two branches insise the github runner environment'
author: 'Seidor'
inputs:
  SOURCE_BRANCH:
    description: 'Source branch name'
    required: true
  TARGET_BRANCH:
    description: 'Target branch name'
    required: true

runs:
  using: composite
  steps:
    - run: /bin/bash $GITHUB_ACTION_PATH/merge.sh source_branch_name=${{ inputs.SOURCE_BRANCH }} target_branch_name=${{ inputs.TARGET_BRANCH }}
      shell: bash