name: 'zip-and-import'
description: 'Zips and imports metadata'
author: 'Seidor'

runs:
  using: composite
  steps:
    - name: 'ZIP and import metadata'
      shell: bash -e {0}
      run: |
        echo "Zipping metadata..."
        echo "zip -qq -r metadata.zip metadata"
        echo "Uploading and importing metadata..."
        echo "sfcc-ci instance:upload metadata.zip"
        echo "sfcc-ci instance:import metadata.zip -s -f"
        echo "Metadata imported"
