name: 'Build SAP Commerce'
description: 'A simple GitHub to build SAP Commerce'
author: 'Seidor'
inputs:
  INITIALIZE:
    description: 'Initialize SAP Commerce data'
    required: false
    default: "0"
  CUSTOM_DIR:
    description: 'Project directory'
    required: false
    default: "/opt/cxcommerce/custom-cx"
  ENVIRONMENT:
    description: 'ANT environment target'
    required: false
    default: "cicd"

runs:
  using: composite
  steps:
    - run: |
          ls -la $GITHUB_ACTION_PATH
          /bin/bash $GITHUB_ACTION_PATH/build.sh initialize=${{ inputs.INITIALIZE }} custom_dir=${{ inputs.CUSTOM_DIR }} environment=${{ inputs.ENVIRONMENT }} project_dir=${{ inputs.PROJECT_DIR }}
      shell: bash