name: 'Scann brnach on SonarQube'
description: 'A simple GitHub Action for build and publish container images over Github Container Registry'
author: 'Seidor'
inputs:
  INITIALIZE:
    description: 'Initialize SAP Commerce data'
    required: false
    default: "0"
  CUSTOM_DIR:
    description: 'Custom modules directory'
    required: false
    default: "core-customize/hybris/bin/custom"
  ENVIRONMENT:
    description: 'ANT environment target'
    required: false
    default: "cicd"

runs:
  using: composite
  steps:
    - run: /bin/bash $GITHUB_ACTION_PATH/build.sh initialize=${{ inputs.INITIALIZE }} custom_dir=${{ inputs.CUSTOM_DIR }} environment=${{ inputs.ENVIRONMENT }}
      shell: bash