name: Build and not push Container Image on Github registry
on:
  workflow_call:
    inputs:
      BUILD_ARGS:
        type: string
        description: 'Extra arguments to pass to kaniko'
        required: false
      IMAGE:
        type: string
        description: 'Image name to use'
        required: false
      TAG:
        type: string
        description: 'Tag to use'
        required: false
      CONTEXT:
        type: string
        description: 'Context to use'
        required: false
        default: .
      DOCKERFILE:
        type: string
        description: 'Dockerfile to use'
        required: false
        default: Dockerfile

jobs:
  build:
    runs-on: 'k8s-ci'
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set Tag Value
      id: set_tag_value
      run: |
            TAG=$(echo ${{ inputs.TAG }})
            if [ -z "${TAG}" ]; then
              TAG=$(grep -i "version" ${{ inputs.CONTEXT }}/${{ inputs.DOCKERFILE }} |cut -d '=' -f2|cut -d '"' -f2)
            fi
            if [ -z "${TAG}" ]; then
              TAG=$(echo ${{ github.sha }})
            fi
            echo TAG=$TAG
            echo "TAG=$TAG" >> $GITHUB_OUTPUT
    - name: Set Image Name Value
      id: set_image_value
      run: |
            IMAGE=$(echo ${{ inputs.IMAGE }})
            if [ -z "$IMAGE" ]; then
              IMAGE=$(grep -i "name" ${{ inputs.CONTEXT }}/${{ inputs.DOCKERFILE }} |cut -d '=' -f2|cut -d '"' -f2)
            fi
            if [ -z "$IMAGE" ]; then
              IMAGE=$(echo $GITHUB_REPOSITORY | cut -d '/' -f2)
            fi
            echo IMAGE=$IMAGE
            echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
    - name: Set BUILD_ARGS Value
      id: set_BUILD_ARGS_value
      run: |
            build_args=${{ inputs.BUILD_ARGS }}
            BUILD_ARGS="${build_args[0]}"
            for arg in ${build_args[@]:1}; do
              BUILD_ARGS="$BUILD_ARGS --build-arg \"$arg\" "
            done
            echo "BUILD_ARGS=$BUILD_ARGS"
            echo "BUILD_ARGS=$BUILD_ARGS" >> $GITHUB_OUTPUT
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Container
      id: build-job
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.CONTEXT }}
        file: ${{ inputs.CONTEXT }}/${{ inputs.DOCKERFILE }}
        push: false
        tags: ghcr.io/${{ github.repository }}/${{ steps.set_image_value.outputs.IMAGE }}:${{ steps.set_tag_value.outputs.TAG }}
        build-args: ${{ steps.set_BUILD_ARGS_value.outputs.BUILD_ARGS }}