name: Build and not push Container Image on Github registry
on:
  workflow_call:
    inputs:
      EXTRA_ARGS:
        type: string
        description: 'Extra arguments to pass to kaniko'
        required: false
      IMAGE:
        type: string
        description: 'Image name to use'
        required: false
      TAG:
        type: string
        description: 'Tag to use'
        required: false
      CONTEXT:
        type: string
        description: 'Context to use'
        required: false
        default: .
      DOCKERFILE:
        type: string
        description: 'Dockerfile to use'
        required: false
        default: Dockerfile
      DEBUG:
        type: string
        description: Enables trace for entrypoint.sh
        required: false
        default: "false"

jobs:
  build:
    runs-on: 'k8s-ci'
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set Tag Value
      id: set_tag_value
      run: |
            TAG=$(echo ${{ inputs.TAG }})
            if [ -z "${TAG}" ]; then
              TAG=$(grep -i "version" Dockerfile |cut -d '=' -f2|cut -d '"' -f2)
            fi
            echo TAG=$TAG
            echo "TAG=$TAG" >> $GITHUB_OUTPUT
    - name: Set Image Name Value
      id: set_image_value
      run: |
            IMAGE=$(echo ${{ inputs.IMAGE }})
            if [ -z "$IMAGE" ]; then
              IMAGE=$(grep -i "name" Dockerfile |cut -d '=' -f2|cut -d '"' -f2)
            fi
            if [ -z "$IMAGE" ]; then
              IMAGE=$(echo $GITHUB_REPOSITORY | cut -d '/' -f2)
            fi
            echo IMAGE=$IMAGE
            echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
    - name: Set EXTRA_ARGS Value
      id: set_extra_args_value
      run: |
            EXTRA_ARGS=$(echo ${{ inputs.EXTRA_ARGS }})
            echo EXTRA_ARGS=$EXTRA_ARGS
            echo "EXTRA_ARGS=$EXTRA_ARGS" >> $GITHUB_OUTPUT
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Container
      id: build-job
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.CONTEXT }}
        file: ${{ inputs.DOCKERFILE }}
        push: false
        tags: ghcr.io/${{ github.repository }}:${{ steps.set_tag_value.outputs.TAG }}
        build-args: ${{ steps.set_extra_args_value.outputs.EXTRA_ARGS }}