name: Build and not push Container Image on Github registry
on:
  workflow_call:
    inputs:
      EXTRA_ARGS:
        type: string
        description: 'Extra arguments to pass to kaniko'
        required: false
      IMAGE:
        type: string
        description: 'Image name to use'
        required: false
      TAG:
        type: string
        description: 'Tag to use'
        required: false

jobs:
  build:
    runs-on: 'k8s-ci'
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set Tag Value
      id: set_tag_value
      run: |
            if [ -n "${{ github.event.inputs.TAG }}" ]; then
              export TAG=${{ github.event.inputs.TAG }}
            else
              export TAG=$(grep -i "version" Dockerfile |cut -d '=' -f2)
            fi
            echo TAG=$TAG
            echo "TAG=$TAG" >> $GITHUB_OUTPUT
    - name: Set Image Name Value
      id: set_image_value
      run: |
            if [ -n "${{ github.event.inputs.IMAGE }}" ]; then
              export IMAGE=${{ github.event.inputs.IMAGE }}
            fi
            if [ -z "$IMAGE" ]; then
              IMAGE=$(grep -i "name" Dockerfile |cut -d '=' -f2)
            else
              IMAGE=$(echo $GITHUB_REPOSITORY | cut -d '/' -f2)
            fi
            echo IMAGE=$IMAGE
            echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
    - name: Build Container
      uses: aevea/action-kaniko@v0.10.0
      with:
        registry: ghcr.io
        password: ${{ secrets.GITHUB_TOKEN }}
        path: .
        image: ${{ steps.set_image_value.outputs.IMAGE }}
        tag: ${{ steps.set_tag_value.outputs.TAG }}
        extra_args: --no-push ${{ github.event.inputs.EXTRA_ARGS }}