name: Build and push Container Image on Github registry
on:
  workflow_call:
    inputs:
      EXTRA_ARGS:
        type: string
        description: 'Extra arguments to pass to kaniko'
        required: false
      IMAGE:
        type: string
        description: 'Image name to use'
        required: false
      TAG:
        type: string
        description: 'Tag to use'
        required: false

jobs:
  build_and_push:
    runs-on: 'k8s-ci'
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set Tag Value
      id: set_tag_value
      run: |
            TAG=$(echo ${{ inputs.TAG }})
            if [ -z "${TAG}" ]; then
              TAG=$(grep -i "version" Dockerfile |cut -d '=' -f2|cut -d '"' -f2)
            fi
            echo TAG=$TAG
            echo "TAG=$TAG" >> $GITHUB_OUTPUT
    - name: Set Image Name Value
      id: set_image_value
      run: |
            IMAGE=$(echo ${{ inputs.IMAGE }})
            if [ -z "$IMAGE" ]; then
              IMAGE=$(grep -i "name" Dockerfile |cut -d '=' -f2|cut -d '"' -f2)
            fi
            if [ -z "$IMAGE" ]; then
              IMAGE=$(echo $GITHUB_REPOSITORY | cut -d '/' -f2)
            fi
            echo IMAGE=$IMAGE
            echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
    - name: Set EXTRA_ARGS Value
      id: set_extra_args_value
      run: |
            EXTRA_ARGS=$(echo ${{ inputs.EXTRA_ARGS }})
            echo EXTRA_ARGS=$EXTRA_ARGS
            echo "EXTRA_ARGS=$EXTRA_ARGS" >> $GITHUB_OUTPUT
    - name: Build Container
      uses: aevea/action-kaniko@v0.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        path: .
        image: ${{ steps.set_image_value.outputs.IMAGE }}
        tag: ${{ steps.set_tag_value.outputs.TAG }}
        extra_args: ${{ steps.set_extra_args_value.outputs.EXTRA_ARGS }} --destination ghcr.io/${{ github.repository }}/${{ steps.set_image_value.outputs.IMAGE }}:latest 